sudo: false
dist: trusty
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_script:
- chmod +x scripts/docs
script:
- yarn cover -- --runInBand
after_success:
- scripts/docs
env:
  global:
    secure: CcW9FPG3APriq6oJ7/Cz/UVsFf3w8b7iU72y32FVDOu5AiLTq9qo/Aj+cBijnSqnaQ24w+NJ5F+OIC42e0D9wyKM+ry+xJ1LAQCMjhOyi30TyOQo/hZOWnNSd0ksln05OdgW9HKHe3pLF23Rfs9aMGwSnyj1AWtytwoLt3K6WmTXDULDtjP1kn35yprMtMV7XzExDb64/k82xT7V5x+MM0Hkm04yCCziQ90M705736I4wpD0J4ufz04QMuV5j/gKmCVSxNCNJxi5McVfWc9UKJ7pJcHjxmWGOuEwxypuy6wvHU9o70ttrHElFuAGqULuwZKKU9hNC7zPo1GmqeFrGAHDGqbSL5v4qtXbuUddcboLbofuc3NxaEsTx/wzEK8gV496P+JqIpHDh7sn/OMMuAE/5Ug9gfOdFyOrmQHxl4Y46ZfM2/aqnDHGydbgkylX3D0QFFAs+NBWoIn0aFZtcpMypMgf+oLRttJWwAZeIn4kp2qfBOpaRAaXT7C0Nb6Gn0rDr5bQcyOtvkF8n8ErRFMG0R765IeOY/U4RJT6nG/GU7eF83fa2jgSruSbRZtzSW/vedyjdbdsATH6yXDx/XnAu1K8C65BRkty8szkLHpv11gn1PeF2wOrEnqXFQMvTKQDjgo3oQCKL8PnR4VfinSJgUApjLN2YWu+b4yZhvc=
before_deploy:
- yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: junminliu@gmail.com
  api_key:
    secure: HUZ9iQCzdcDBbkmvT4kmZbhYzc4KtvijP7PTt33MJ2eIFXpNK+E6ynO/8/UGR7Re6aersR1nm5LOiaLqwuoCvMxwqbVGvOd7dRjlKQG4twKFvze3fpvEpJWP+ZK1y4VK2QTyD2LjS7ocXX2Yi7PindNjbt4N5PMVUFBAIlp2GoeIXRz3qKieVuLMnV2Y/SPzIVufM3IGutP2WtEFnf++e3VVAkQaL6DykyYmHdsCBzOXQ7I7axeQqYOh9DjlxSeLq1G6ntLp4IHwVGUXeEhvbndSa1P70Fa70L7O+80fPBuvn/B077j0jceSRCbVzNG2pgS0MstM4loUq2nMjxV7OaLPe8Zf4zmGUiALkhS4YFaylPRCLfnY/ekXht5dJrTjPQACsbs74XOyOdWl8KNtKS3hj6uiftLnAMOf/2Tb5UUrcvFxEQS1+aZjMVTWk1c528FUUhVbDPskq5GqUSSxeUhlQRb+oMIX6Vins0YAM5GGcxJ/COTpRWfM82/8Cy6myw7qTo8u7MnXql5jSmDaDtWFnysLzkLVrKxlMDuXuQpxTRP/vL/4YCgxO0OJb2XBgvglJ0UKcDpDBQIvLtnFpSmdvjlwi7TUtNLEjJ2WsR86cST7uloR+mYZWM3sslAhf+aSLT2ShzLMG5N11cfQeEBRPcuEM4qt8rtfjeGUOMA=
  on:
    tags: true
    all_branches: true
    repo: video-react/video-react
